# name of the action
name: prerelease

# trigger on push events with `v*` in tag
on:
  push:
    tags:
      - 'v*'

# pipeline to execute
jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      with:
        # ensures we fetch tag history for the repository
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: setup
      run: |
        # setup git tag in Actions environment
        echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: |
        make build-static-ci

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-slack
        cache: true
        tag_names: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
