# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: install go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: test
      run: |
        go test -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: coverage
      uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8 # v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out
